name: kontrol_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.12
  get_it: ^8.0.3
  go_router: ^14.8.1
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4

dependency_overrides:
  analyzer: ^7.4.0

flutter:
  uses-material-design: true
  assets:
    - .env
